### ISSUE TITLE
What is special about it?

### ISSUE THREAD

**Issue by TonyPythoneer** [kennethreitz/dj-database-url#61]
It's just changed from dict config to invoking function of this package to do connection.

I have read 12factor but I don't still understand.

Anyone can answer?

**Comment by kennethreitz** [comment]
This packages allows you to use a URL to declare your database connections, instead of dictionaries. Many web services (like Heroku Postgres) provide URLs that contain connection information. 

This module also promotes the use of not hardcoding your credentials into your Django codebase, and instead using environment variables to pass them in (like arguments) to your application at runtime.
